name: california-vehicle-payment
dependencies:
- python
- pip
- pip:
  - jupyter-book
  - microdf_python
  - "git+https://github.com/ubicenter/ubicenter.py"
  - argparse
  - pyyaml
  - pathlib
  - typing
  - numpy
  - pandas
  - plotly